<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <artifactId>searchstateexplorer-examples</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>pom</packaging>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
  </properties>
 
  <parent>
    <groupId>it.uniroma1.di.tmancini.teaching.ai.search</groupId>
    <artifactId>searchstateexplorer</artifactId>
    <version>1.0-SNAPSHOT</version>
  </parent>
 

  <modules>
    <module>Puzzle</module>
    <module>Vacuum</module>
    <module>ProteinFolding</module>
  </modules>

  <build>
    <finalName>searchstateexplorer-examples</finalName>
  </build>
</project>
